# Generated by Django 5.2.7 on 2025-12-28 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('platform', models.CharField(choices=[('workday', 'Workday'), ('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('ashby', 'Ashby')], max_length=50)),
                ('active', models.BooleanField(default=True, help_text='Whether to include this company in job syncing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkdayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(help_text='e.g., https://company.wd5.myworkdayjobs.com')),
                ('tenant', models.CharField(help_text='e.g., company_name', max_length=100)),
                ('site', models.CharField(help_text='e.g., company_careers', max_length=100)),
                ('location_filters', models.JSONField(blank=True, default=dict, help_text='JSON mapping location names to IDs: {"Seattle": "abc123..."}')),
                ('company', models.OneToOneField(limit_choices_to={'platform': 'workday'}, on_delete=django.db.models.deletion.CASCADE, related_name='workday_config', to='jobs.company')),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Job ID from the platform', max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(max_length=1000)),
                ('posted_on', models.CharField(blank=True, max_length=100)),
                ('seen', models.BooleanField(default=False, help_text='User has reviewed this job')),
                ('interested', models.BooleanField(default=False, help_text='User marked as potentially interesting')),
                ('dismissed', models.BooleanField(default=False, help_text='User dismissed as not a fit')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_fetched', models.DateTimeField(auto_now=True, help_text='Last time this job appeared in API results')),
                ('is_stale', models.BooleanField(default=False, help_text='No longer appears in API results')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to='jobs.company')),
            ],
            options={
                'ordering': ['-first_seen'],
                'indexes': [models.Index(fields=['seen', 'is_stale', 'dismissed'], name='jobs_joblis_seen_4a3e55_idx'), models.Index(fields=['company', 'external_id'], name='jobs_joblis_company_1bddaf_idx')],
                'unique_together': {('company', 'external_id')},
            },
        ),
    ]
