# Generated by Django 5.2.7 on 2025-12-29 06:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='last_fetched',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time this job appeared in API results'),
        ),
    ]
