# Generated by Django 5.2.7 on 2025-12-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_joblisting_last_fetched'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joblisting',
            options={'ordering': ['-last_fetched']},
        ),
        migrations.RemoveIndex(
            model_name='joblisting',
            name='jobs_joblis_seen_4a3e55_idx',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='dismissed',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='interested',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='seen',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('interested', 'Interested'), ('dismissed', 'Dismissed'), ('applied', 'Applied')], default='new', help_text='Current review status of this job listing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['status', 'is_stale'], name='jobs_joblis_status_def3d2_idx'),
        ),
    ]
