# Generated by Django 5.2.7 on 2025-12-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_joblisting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='public_site_url',
            field=models.URLField(blank=True, help_text='Base URL for public job listings (e.g., https://nordstrom.wd501.myworkdayjobs.com/en-US/nordstrom_careers/)', max_length=500),
        ),
    ]
