# Generated by Django 5.2.7 on 2025-12-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_company_public_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='url_path',
            field=models.CharField(default='', help_text='Relative job path from API', max_length=1000),
            preserve_default=False,
        ),
    ]
