# Generated by Django 5.2.7 on 2025-12-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_joblisting_url_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='url',
        ),
    ]
