# Generated by Django 5.2.7 on 2025-12-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_joblisting_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('analytics_engineer', 'Analytics Engineer'), ('business_analyst', 'Business Analyst'), ('business_intelligence_engineer', 'Business Intelligence Engineer'), ('data_analyst', 'Data Analyst'), ('data_engineer', 'Data Engineer'), ('data_scientist', 'Data Scientist'), ('software_engineer', 'Software Engineer'), ('solutions_engineer', 'Solutions Engineer')], help_text='Role to configure search behavior for', max_length=100, unique=True)),
                ('exclude_terms', models.JSONField(default=list, help_text='Terms to exclude from job titles for this role')),
            ],
            options={
                'verbose_name': 'Search Role Configuration',
                'verbose_name_plural': 'Search Role Configurations',
            },
        ),
        migrations.AddField(
            model_name='joblisting',
            name='search_role',
            field=models.CharField(blank=True, choices=[('analytics_engineer', 'Analytics Engineer'), ('business_analyst', 'Business Analyst'), ('business_intelligence_engineer', 'Business Intelligence Engineer'), ('data_analyst', 'Data Analyst'), ('data_engineer', 'Data Engineer'), ('data_scientist', 'Data Scientist'), ('software_engineer', 'Software Engineer'), ('solutions_engineer', 'Solutions Engineer')], help_text='Role category this job was fetched for', max_length=100),
        ),
    ]
