# Generated by Django 5.2.7 on 2025-12-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_searchroleconfig_joblisting_search_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(help_text="Primary search keyword (e.g., 'Software Engineer', 'Data Analyst')", max_length=200, unique=True)),
                ('exclude_terms', models.JSONField(default=list, help_text='Terms to exclude from job titles')),
                ('active', models.BooleanField(default=True, help_text='Include in automated syncs')),
            ],
            options={
                'verbose_name': 'Search Configuration',
                'verbose_name_plural': 'Search Configurations',
            },
        ),
    ]
