# Generated by Django 5.2.7 on 2025-12-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_searchconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='search_role',
        ),
    ]
