# Generated by Django 5.2.7 on 2025-12-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_joblisting_search_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchRoleConfig',
        ),
    ]
