# Generated by Django 5.2.7 on 2025-12-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_delete_searchroleconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchconfig',
            name='exclude_terms',
            field=models.JSONField(blank=True, default=list, help_text='Terms to exclude from job titles'),
        ),
    ]
