# Generated by Django 5.2.7 on 2025-12-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_searchconfig_exclude_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='search_term',
            field=models.CharField(blank=True, help_text='Search keyword used to fetch this job (from SearchRole label)', max_length=100),
        ),
    ]
