# Generated by Django 5.2.7 on 2025-12-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_joblisting_search_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='search_term',
            field=models.CharField(blank=True, help_text='Search keyword used to fetch this job (from SearchConfig)', max_length=100),
        ),
    ]
