# Generated by Django 5.2.7 on 2026-01-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_joblisting_search_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='exclude_terms',
            field=models.JSONField(blank=True, default=list, help_text='Terms to exclude from job titles'),
        ),
    ]
