# Generated by Django 5.2.7 on 2026-01-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_company_exclude_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchconfig',
            name='related_terms',
            field=models.JSONField(blank=True, default=list, help_text="List of related search terms sharing the same exclusion rules (e.g., ['Software Developer'])"),
        ),
    ]
