# Generated by Django 5.2.7 on 2025-10-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(choices=[('Analytics Engineer', 'Analytics Engineer'), ('Business Analyst', 'Business Analyst'), ('Business Intelligence Engineer', 'Business Intelligence Engineer'), ('Data Analyst', 'Data Analyst'), ('Data Engineer', 'Data Engineer'), ('Software Engineer', 'Software Engineer')], help_text="Target role for this template (e.g., 'Software Engineer').", max_length=64)),
                ('target_level', models.CharField(choices=[('I', 'I'), ('II', 'Ii'), ('III', 'Iii'), ('Senior', 'Senior')], help_text="Target seniority level (e.g., 'II', 'Senior').", max_length=16)),
                ('template_path', models.CharField(help_text='Path to the Markdown template file.', max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('target_role', 'target_level'), name='unique_role_level_template')],
            },
        ),
    ]
