# Generated by Django 5.2.7 on 2025-10-18 20:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
        ('tracker', '0003_alter_requirement_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unmet_requirements', models.TextField(blank=True, default='', help_text="CSV string of unmatched tools/technologies (e.g., 'Go,Ruby on Rails').")),
                ('match_ratio', models.FloatField(default=0.0, help_text='Fraction of requirements met (0.0 to 1.0).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('job', models.OneToOneField(help_text='Job listing this resume targets.', on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='tracker.job')),
                ('template', models.ForeignKey(help_text='Template used to generate this resume.', on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='resume.resumetemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['template'], name='resume_resu_templat_c450ea_idx')],
            },
        ),
    ]
