# Generated by Django 5.2.7 on 2025-10-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('navit', 'Nav.it'), ('amazon_sde', 'Amazon SDE'), ('amazon_bie', 'Amazon BIE'), ('darigold', 'Darigold'), ('avenu', 'Avenu')], help_text="Stable identifier used by templates (e.g., 'navit', 'amazon_sde').", max_length=50, unique=True)),
                ('company', models.CharField(help_text="Employer name (e.g., 'Nav.it').", max_length=255)),
                ('title', models.CharField(help_text="Job title (e.g., 'Software Engineer').", max_length=255)),
                ('display_name', models.CharField(blank=True, default='', help_text="Optional human-facing name; if empty, renders as 'title – company'.", max_length=255)),
            ],
        ),
    ]
