# Generated by Django 5.2.7 on 2025-10-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_experiencerole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencerole',
            name='key',
            field=models.CharField(help_text="Stable identifier used by templates (e.g., 'navit', 'amazon_sde').", max_length=50, unique=True),
        ),
    ]
