# Generated by Django 5.2.7 on 2025-10-19 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_experiencerole_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text="Short label for the project/task (e.g., 'Search API Redesign').", max_length=255)),
                ('problem_context', models.TextField(help_text='Concise problem statement describing the challenge addressed.')),
                ('actions', models.CharField(help_text="Comma-separated list of action items (e.g., 'implemented X, rewrote Y').", max_length=1000)),
                ('tools', models.CharField(help_text="Comma-separated list of tools/technologies (e.g., 'Django,Postgres').", max_length=500)),
                ('outcomes', models.CharField(help_text="Comma-separated list of short outcomes (e.g., 'reduced latency 80%').", max_length=1000)),
                ('impact_area', models.CharField(help_text="Category describing the type of impact (e.g., 'Performance Optimization', 'User Engagement').", max_length=255)),
                ('experience_role', models.ForeignKey(help_text='The role during which this project was completed.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resume.experiencerole')),
            ],
        ),
    ]
