# Generated by Django 5.2.7 on 2025-10-19 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_experienceproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateRoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.BooleanField(default=True, help_text='Whether to include this role when rendering the template.')),
                ('max_bullet_count', models.PositiveIntegerField(help_text='Maximum number of bullets to generate for this role.')),
                ('experience_role', models.ForeignKey(help_text='The experience role to configure for this template.', on_delete=django.db.models.deletion.CASCADE, related_name='template_configs', to='resume.experiencerole')),
                ('template', models.ForeignKey(help_text='The resume template this configuration belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='role_configs', to='resume.resumetemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('template', 'experience_role'), name='unique_template_experience_role')],
            },
        ),
    ]
