# Generated by Django 5.2.7 on 2025-10-20 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_templateroleconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeExperienceBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Display order within the resume.')),
                ('text', models.TextField(help_text='Generated bullet content.')),
                ('exclude', models.BooleanField(default=False, help_text='Whether to exclude this bullet from the rendered resume.')),
                ('override_text', models.TextField(blank=True, default='', help_text='Optional manually edited version that takes priority over text.')),
                ('experience_role', models.ForeignKey(help_text='Experience role this bullet was generated for.', on_delete=django.db.models.deletion.CASCADE, related_name='resume_bullets', to='resume.experiencerole')),
                ('resume', models.ForeignKey(help_text='Resume this bullet belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='experience_bullets', to='resume.resume')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['resume', 'order'], name='resume_resu_resume__6ba0d8_idx'), models.Index(fields=['experience_role'], name='resume_resu_experie_4a4dff_idx')],
            },
        ),
    ]
