# Generated by Django 5.2.7 on 2025-10-21 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_resumeexperiencebullet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSkillBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text="Category label such as 'Programming Languages' or 'Data & Visualization'.", max_length=255)),
                ('skills_text', models.TextField(help_text="CSV string of related skills (e.g., 'Python, Java').")),
                ('resume', models.ForeignKey(help_text='Resume this skill bullet belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='skill_bullets', to='resume.resume')),
            ],
        ),
    ]
