# Generated by Django 5.2.7 on 2025-10-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_resumeskillbullet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateroleconfig',
            name='include',
        ),
        migrations.AddField(
            model_name='templateroleconfig',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Display order for this role within the template (lower values appear first).'),
            preserve_default=False,
        ),
    ]
