# Generated by Django 5.2.7 on 2025-10-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_remove_templateroleconfig_include_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='style_path',
            field=models.CharField(default='resume/templates/css/resume.css', help_text='Path to the CSS stylesheet file.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='template_path',
            field=models.CharField(help_text='Path to the HTML template file.', max_length=255),
        ),
    ]
