# Generated by Django 5.2.7 on 2025-11-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_resumetemplate_style_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceproject',
            name='actions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='experienceproject',
            name='outcomes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='experienceproject',
            name='tools',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='experiencerole',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text="Optional human-facing name; if empty, renders as 'title - company'.", max_length=255),
        ),
    ]
