# Generated by Django 5.2.7 on 2025-11-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_alter_experienceproject_actions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='match_ratio',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='unmet_requirements',
        ),
    ]
