# Generated by Django 5.2.7 on 2025-11-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_remove_resume_match_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetemplate',
            name='style_path',
            field=models.CharField(choices=[('css/resume_compact.css', 'Compact'), ('css/resume_standard.css', 'Standard')], help_text='Path to the CSS stylesheet file.', max_length=255),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='template_path',
            field=models.CharField(choices=[('html/software_engineer_i.html', 'Software Engineer I'), ('html/software_engineer_ii.html', 'Software Engineer II')], help_text='Path to the HTML template file.', max_length=255),
        ),
    ]
