# Generated by Django 5.2.7 on 2025-11-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_alter_resumetemplate_style_path_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resumetemplate',
            name='unique_role_level_template',
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='target_specialization',
            field=models.CharField(blank=True, choices=[('Backend', 'Backend'), ('Python', 'Python')], help_text="Optional specialization (e.g., 'Backend', 'Python').", max_length=16, null=True),
        ),
        migrations.AddConstraint(
            model_name='resumetemplate',
            constraint=models.UniqueConstraint(fields=('target_role', 'target_level', 'target_specialization'), name='unique_role_level_specialization'),
        ),
        migrations.AddConstraint(
            model_name='resumetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('target_specialization__isnull', True)), fields=('target_role', 'target_level'), name='unique_role_level_no_specialization'),
        ),
    ]
