# Generated by Django 5.2.7 on 2025-11-07 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_remove_resumetemplate_unique_role_level_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencerole',
            name='display_name',
        ),
        migrations.AddField(
            model_name='experiencerole',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date the role ended.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencerole',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date the role began.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='template_path',
            field=models.CharField(choices=[('html/analyst.html', 'Analyst'), ('html/engineer.html', 'Engineer')], help_text='Path to the HTML template file.', max_length=255),
        ),
    ]
