# Generated by Django 5.2.7 on 2025-11-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_remove_experiencerole_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateroleconfig',
            name='title_override',
            field=models.CharField(blank=True, help_text="Experience roole title override (e.g., 'Software Engineer (Data Systems)').", max_length=64, null=True),
        ),
    ]
