# Generated by Django 5.2.7 on 2025-11-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_templateroleconfig_title_override'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='templateroleconfig',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='unique_template_order'),
        ),
    ]
