# Generated by Django 5.2.7 on 2025-11-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_templateroleconfig_unique_template_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencerole',
            name='location',
            field=models.CharField(default='', help_text="Location where the role was set in. (e.g 'Seattle, WA', 'Remote')", max_length=50),
            preserve_default=False,
        ),
    ]
