# Generated by Django 5.2.7 on 2025-11-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_experiencerole_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienceproject',
            name='impact_area',
        ),
    ]
