# Generated by Django 5.2.7 on 2025-11-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_remove_experienceproject_impact_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
