# Generated by Django 5.2.7 on 2025-11-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_resume_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetemplate',
            name='style_path',
            field=models.CharField(choices=[('css/resume_compact.css', 'Compact'), ('css/resume_dense.css', 'Dense'), ('css/resume_standard.css', 'Standard')], help_text='Path to the CSS stylesheet file.', max_length=255),
        ),
    ]
