# Generated by Django 5.2.7 on 2025-11-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('resume', '0022_remove_resumeexperiencebullet_resume_resu_resume__6ba0d8_idx_and_more'), ('resume', '0023_alter_resumeexperiencebullet_options'), ('resume', '0024_auto_20251111_1235'), ('resume', '0025_alter_resumeexperiencebullet_role_bullet_order'), ('resume', '0026_resumeexperiencebullet_role_order'), ('resume', '0027_alter_resumeexperiencebullet_options'), ('resume', '0028_resumeexperiencebullet_resume_resu_resume__a51bff_idx'), ('resume', '0029_alter_resumeexperiencebullet_role_order'), ('resume', '0030_resumeexperiencebullet_unique_resume_role_order_role_bullet_order')]

    dependencies = [
        ('resume', '0021_alter_resumetemplate_style_path'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resumeexperiencebullet',
            name='resume_resu_resume__6ba0d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='resumeexperiencebullet',
            name='resume_resu_experie_4a4dff_idx',
        ),
        migrations.AlterModelOptions(
            name='resumeexperiencebullet',
            options={},
        ),
        migrations.RenameField(
            model_name='resumeexperiencebullet',
            old_name='order',
            new_name='role_bullet_order',
        ),
        migrations.AlterField(
            model_name='resumeexperiencebullet',
            name='role_bullet_order',
            field=models.PositiveIntegerField(help_text='Bullet display order within the role.'),
        ),
        migrations.AddField(
            model_name='resumeexperiencebullet',
            name='role_order',
            field=models.PositiveIntegerField(blank=True, help_text='Role order within the resume.', null=True),
        ),
        migrations.AlterModelOptions(
            name='resumeexperiencebullet',
            options={'ordering': ['role_order', 'role_bullet_order']},
        ),
        migrations.AddIndex(
            model_name='resumeexperiencebullet',
            index=models.Index(fields=['resume', 'role_order', 'role_bullet_order'], name='resume_resu_resume__a51bff_idx'),
        ),
        migrations.AlterField(
            model_name='resumeexperiencebullet',
            name='role_order',
            field=models.PositiveIntegerField(help_text='Role order within the resume.'),
        ),
        migrations.AddConstraint(
            model_name='resumeexperiencebullet',
            constraint=models.UniqueConstraint(fields=('resume', 'role_order', 'role_bullet_order'), name='unique_resume_role_order_role_bullet_order'),
        ),
    ]
