# Generated by Django 5.2.7 on 2025-11-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_remove_resumeexperiencebullet_resume_resu_resume__6ba0d8_idx_and_more_squashed_0030_resumeexperiencebullet_unique_resume_role_order_role_bullet_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeskillbullet',
            name='exclude',
            field=models.BooleanField(default=False, help_text='Whether to exclude this skills category from the rendered resume.'),
        ),
    ]
