# Generated by Django 5.2.7 on 2025-11-13 06:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('resume', '0032_resumeexperiencerole'), ('resume', '0033_resumeexperiencerole_created_at'), ('resume', '0034_alter_resumeexperiencerole_experience_role'), ('resume', '0035_resumeexperiencerolebullet'), ('resume', '0036_resumeskillscategory'), ('resume', '0037_resumeskillscategory_created_at'), ('resume', '0038_remove_resumeexperiencerole_unique_resume_experience_role_and_more'), ('resume', '0039_alter_resumeexperiencerolebullet_override_text'), ('resume', '0040_rename_resumeexperiencerole_resumerole'), ('resume', '0041_remove_resumeexperiencerolebullet_unique_resume_experience_role_order_and_more'), ('resume', '0042_rename_resumeexperiencerolebullet_resumerolebullet'), ('resume', '0043_alter_resumerole_resume'), ('resume', '0044_resumerole_unique_resume_order'), ('resume', '0045_remove_resumeskillbullet_resume_and_more')]

    dependencies = [
        ('resume', '0031_resumeskillbullet_exclude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeExperienceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Frozen title used in this resume (copied from override_title or experience_role.title).', max_length=255)),
                ('order', models.PositiveIntegerField(help_text='Display order of this role within the resume.')),
                ('experience_role', models.ForeignKey(help_text='Original experience role used as the source.', on_delete=django.db.models.deletion.PROTECT, to='resume.experiencerole')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_roles', to='resume.resume')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('resume', 'experience_role'), name='unique_resume_experience_role')],
            },
        ),
        migrations.CreateModel(
            name='ResumeExperienceRoleBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Original bullet content.')),
                ('override_text', models.TextField(blank=True, help_text='Optional edited version of the bullet that overrides `text`.', null=True)),
                ('order', models.PositiveIntegerField(help_text='Display order within the role.')),
                ('exclude', models.BooleanField(default=False, help_text='Whether to exclude this bullet from the rendered resume.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_experience_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='resume.resumeexperiencerole')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('resume_experience_role', 'order'), name='unique_resume_experience_role_order')],
            },
        ),
        migrations.CreateModel(
            name='ResumeSkillsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Display order of this category within the resume.')),
                ('category', models.CharField(help_text='Category label such as "Programming Languages" or "Data & Visualization".', max_length=255)),
                ('skills_text', models.TextField(help_text='CSV string of related skills (e.g., "Python, Java").')),
                ('exclude', models.BooleanField(default=False, help_text='Whether to exclude this category from rendering.')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_categories', to='resume.resume')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='resumeexperiencerole',
            name='unique_resume_experience_role',
        ),
        migrations.RenameField(
            model_name='resumeexperiencerole',
            old_name='experience_role',
            new_name='source_role',
        ),
        migrations.AlterField(
            model_name='resumeexperiencerole',
            name='title',
            field=models.CharField(help_text='Frozen title used in this resume (copied from override_title or source_role.title).', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='resumeexperiencerole',
            constraint=models.UniqueConstraint(fields=('resume', 'source_role'), name='unique_resume_source_role'),
        ),
        migrations.AlterField(
            model_name='resumeexperiencerolebullet',
            name='override_text',
            field=models.TextField(default='', help_text='Optional edited version of the bullet that overrides `text`.', null=True),
        ),
        migrations.RenameModel(
            old_name='ResumeExperienceRole',
            new_name='ResumeRole',
        ),
        migrations.RemoveConstraint(
            model_name='resumeexperiencerolebullet',
            name='unique_resume_experience_role_order',
        ),
        migrations.RenameField(
            model_name='resumeexperiencerolebullet',
            old_name='resume_experience_role',
            new_name='resume_role',
        ),
        migrations.AddConstraint(
            model_name='resumeexperiencerolebullet',
            constraint=models.UniqueConstraint(fields=('resume_role', 'order'), name='unique_resume_role_order'),
        ),
        migrations.RenameModel(
            old_name='ResumeExperienceRoleBullet',
            new_name='ResumeRoleBullet',
        ),
        migrations.AlterField(
            model_name='resumerole',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='resume.resume'),
        ),
        migrations.AddConstraint(
            model_name='resumerole',
            constraint=models.UniqueConstraint(fields=('resume', 'order'), name='unique_resume_order'),
        ),
        migrations.RemoveField(
            model_name='resumeskillbullet',
            name='resume',
        ),
        migrations.DeleteModel(
            name='ResumeExperienceBullet',
        ),
        migrations.DeleteModel(
            name='ResumeSkillBullet',
        ),
    ]
