# Generated by Django 5.2.7 on 2025-11-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0032_resumeexperiencerole_squashed_0045_remove_resumeskillbullet_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumerole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resumerolebullet',
            name='override_text',
            field=models.TextField(blank=True, default='', help_text='Optional edited version of the bullet that overrides `text`.'),
        ),
        migrations.AlterField(
            model_name='resumeskillscategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
