# Generated by Django 5.2.7 on 2025-11-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0046_alter_resumerole_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetemplate',
            name='target_specialization',
            field=models.CharField(blank=True, choices=[('backend', 'Backend'), ('fullstack', 'Full-Stack'), ('python', 'Python')], help_text="Optional specialization (e.g., 'Backend', 'Python').", max_length=16, null=True),
        ),
    ]
