# Generated by Django 5.2.7 on 2025-11-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0047_alter_resumetemplate_target_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='style_path',
            field=models.CharField(choices=[('css/resume_compact.css', 'Compact'), ('css/resume_dense.css', 'Dense'), ('css/resume_standard.css', 'Standard')], default='css/resume_standard.css', help_text='Path to the CSS stylesheet file.', max_length=255),
        ),
    ]
