# Generated by Django 5.2.7 on 2025-11-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0048_resume_style_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='description',
            field=models.CharField(blank=True, help_text="Description for custom templates (e.g., 'SWE II with BI experience')", max_length=255),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Whether this is a custom one-off template vs. a standard reusable template'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='target_role',
            field=models.CharField(choices=[('Analytics Engineer', 'Analytics Engineer'), ('Business Analyst', 'Business Analyst'), ('Business Intelligence Engineer', 'Business Intelligence Engineer'), ('Data Analyst', 'Data Analyst'), ('Data Engineer', 'Data Engineer'), ('Software Engineer', 'Software Engineer'), ('Solutions Engineer', 'Solutions Engineer')], help_text="Target role for this template (e.g., 'Software Engineer').", max_length=64),
        ),
    ]
