# Generated by Django 5.2.7 on 2025-11-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0049_resumetemplate_description_resumetemplate_is_custom_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resumetemplate',
            name='unique_role_level_specialization',
        ),
        migrations.RemoveConstraint(
            model_name='resumetemplate',
            name='unique_role_level_no_specialization',
        ),
        migrations.AddConstraint(
            model_name='resumetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_custom', False)), fields=('target_role', 'target_level', 'target_specialization'), name='unique_role_level_specialization'),
        ),
        migrations.AddConstraint(
            model_name='resumetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_custom', False), ('target_specialization__isnull', True)), fields=('target_role', 'target_level'), name='unique_role_level_no_specialization'),
        ),
    ]
