# Generated by Django 5.2.7 on 2025-12-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0050_remove_resumetemplate_unique_role_level_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeskillscategory',
            name='override_text',
            field=models.TextField(blank=True, default='', help_text='Optional edited version of the bullet that overrides `skills_text`.'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='target_level',
            field=models.CharField(choices=[('associate', 'Associate'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('senior', 'Senior')], help_text="Target seniority level (e.g., 'II', 'Senior').", max_length=16),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='target_role',
            field=models.CharField(choices=[('analytics_engineer', 'Analytics Engineer'), ('business_analyst', 'Business Analyst'), ('business_intelligence_engineer', 'Business Intelligence Engineer'), ('data_analyst', 'Data Analyst'), ('data_engineer', 'Data Engineer'), ('data_scientist', 'Data Scientist'), ('software_engineer', 'Software Engineer'), ('solutions_engineer', 'Solutions Engineer')], help_text="Target role for this template (e.g., 'Software Engineer').", max_length=64),
        ),
    ]
