# Generated by Django 5.2.7 on 2026-01-13 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0051_resumeskillscategory_override_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumerolebullet',
            name='experience_project',
            field=models.ForeignKey(blank=True, help_text='Optional link to the ExperienceProject this bullet is based on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_bullets', to='resume.experienceproject'),
        ),
    ]
