# Generated by Django 5.2.7 on 2025-10-18 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(db_index=True, max_length=255)),
                ('listing_job_title', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(choices=[('Analytics Engineer', 'Analytics Engineer'), ('Business Analyst', 'Business Analyst'), ('Business Intelligence Engineer', 'Business Intelligence Engineer'), ('Data Analyst', 'Data Analyst'), ('Data Engineer', 'Data Engineer'), ('Software Engineer', 'Software Engineer')], db_index=True, max_length=64)),
                ('specialization', models.CharField(blank=True, max_length=128, null=True)),
                ('level', models.CharField(choices=[('I', 'I'), ('II', 'Ii'), ('III', 'Iii'), ('Senior', 'Senior')], max_length=16)),
                ('location', models.CharField(max_length=255)),
                ('work_setting', models.CharField(choices=[('On-site', 'On Site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=16)),
                ('min_experience_years', models.PositiveSmallIntegerField(blank=True, help_text='Minimum years of experience (nullable if not parsed).', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_salary', models.IntegerField(blank=True, help_text='Minimum salary in the job listing (nullable).', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_salary', models.IntegerField(blank=True, help_text='Maximum salary in the job listing (nullable).', null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'role'], name='tracker_job_company_d51cf8_idx')],
            },
        ),
    ]
