# Generated by Django 5.2.7 on 2025-10-18 17:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('relevance', models.FloatField(help_text='Relevance score in the range [0.0, 1.0].', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('order', models.PositiveIntegerField(help_text='Ordering index from the parser (0-based).')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='tracker.job')),
            ],
            options={
                'ordering': ['job', 'order'],
                'indexes': [models.Index(fields=['job', 'relevance'], name='tracker_req_job_id_483e02_idx'), models.Index(fields=['job', 'order'], name='tracker_req_job_id_afb508_idx')],
            },
        ),
    ]
