# Generated by Django 5.2.7 on 2025-10-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='order',
            field=models.PositiveIntegerField(help_text='Ordering index from the parser.'),
        ),
    ]
