# Generated by Django 5.2.7 on 2025-10-31 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_requirement_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='requirement',
            name='tracker_req_job_id_afb508_idx',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='order',
        ),
    ]
