# Generated by Django 5.2.7 on 2025-11-04 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_requirement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('call_type', models.CharField(choices=[('parse_jd', 'Parse Job Description'), ('resume_bullets', 'Resume Bullets'), ('resume_skills', 'Resume Skills')], max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('input_tokens', models.PositiveIntegerField()),
                ('output_tokens', models.PositiveIntegerField()),
            ],
        ),
    ]
