# Generated by Django 5.2.7 on 2025-11-11 02:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_alter_resumetemplate_style_path'),
        ('tracker', '0006_job_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='tracker.job')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Callback', 'Callback'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], max_length=16)),
                ('status_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='tracker.application')),
            ],
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job'], name='tracker_app_job_id_7e0bc7_idx'),
        ),
    ]
