# Generated by Django 5.2.7 on 2025-11-11 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_application_applicationstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
    ]
