# Generated by Django 5.2.7 on 2025-11-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_application_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_date']},
        ),
        migrations.AlterModelOptions(
            name='applicationstatus',
            options={'verbose_name_plural': 'Application Statuses'},
        ),
    ]
