# Generated by Django 5.2.7 on 2025-11-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='desired_salary_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
