# Generated by Django 5.2.7 on 2025-11-17 21:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_application_desired_salary_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(choices=[('Analytics Engineer', 'Analytics Engineer'), ('Business Analyst', 'Business Analyst'), ('Business Intelligence Engineer', 'Business Intelligence Engineer'), ('Data Analyst', 'Data Analyst'), ('Data Engineer', 'Data Engineer'), ('Software Engineer', 'Software Engineer'), ('Solutions Engineer', 'Solutions Engineer')], db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='ContractJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulting_company', models.CharField(blank=True, help_text='Company through which the contract is offered.', max_length=255, null=True)),
                ('contract_length_months', models.PositiveIntegerField(help_text='Duration of the contract in months.', validators=[django.core.validators.MinValueValidator(0)])),
                ('hourly_rate_min', models.IntegerField(blank=True, help_text='Minimum hourly rate quoted in the contract.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('hourly_rate_max', models.IntegerField(blank=True, help_text='Maximum hourly rate quoted in the contract.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('hourly_rate_submitted', models.IntegerField(blank=True, help_text='Hourly rate submitted on the resume/application.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('provides_benefits', models.BooleanField(default=False, help_text='Whether the contract provides benefits.')),
                ('provides_pto', models.BooleanField(default=False, help_text='Whether the contract provides paid time off.')),
                ('job', models.OneToOneField(help_text='Base job this contract role is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='tracker.job')),
            ],
        ),
    ]
