# Generated by Django 5.2.7 on 2025-11-20 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_job_role_contractjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('recruiter_screen', 'Recruiter Screen'), ('technical_screen', 'Technical Screen'), ('final_loop', 'Final Loop')], max_length=50)),
                ('format', models.CharField(blank=True, choices=[('phone_call', 'Phone Call'), ('virtual_meeting', 'Virtual Meeting')], max_length=50)),
                ('focus', models.CharField(blank=True, choices=[('coding', 'Coding'), ('system_design', 'System Design'), ('behavioral', 'Behavioral'), ('hiring_manager', 'Hiring Manager')], max_length=50)),
                ('interviewer_name', models.CharField(blank=True, max_length=200)),
                ('interviewer_title', models.CharField(blank=True, max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='tracker.application')),
            ],
        ),
    ]
