# Generated by Django 5.2.7 on 2025-11-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('Senior', 'Senior')], max_length=16),
        ),
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(choices=[('analytics_engineer', 'Analytics Engineer'), ('business_analyst', 'Business Analyst'), ('business_intelligence_engineer', 'Business Intelligence Engineer'), ('data_analyst', 'Data Analyst'), ('data_engineer', 'Data Engineer'), ('software_engineer', 'Software Engineer'), ('solutions_engineer', 'Solutions Engineer')], db_index=True, max_length=64),
        ),
    ]
