# Generated by Django 5.2.7 on 2025-11-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_job_level_alter_job_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(choices=[('analytics_engineer', 'Analytics Engineer'), ('business_analyst', 'Business Analyst'), ('business_intelligence_engineer', 'Business Intelligence Engineer'), ('data_analyst', 'Data Analyst'), ('data_engineer', 'Data Engineer'), ('data_scientist', 'Data Scientist'), ('software_engineer', 'Software Engineer'), ('solutions_engineer', 'Solutions Engineer')], db_index=True, max_length=64),
        ),
    ]
