# Generated by Django 5.2.7 on 2025-11-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_alter_job_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='notes',
            field=models.TextField(blank=True, help_text='Freeform interview notes'),
        ),
    ]
