# Generated by Django 5.2.7 on 2025-12-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_interview_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='state',
            field=models.CharField(choices=[('callback', 'Callback'), ('closed', 'Closed'), ('rejected', 'Rejected')], max_length=16),
        ),
        migrations.AlterField(
            model_name='interview',
            name='stage',
            field=models.CharField(choices=[('recruiter_screen', 'Recruiter Screen'), ('hiring_manager_screen', 'Hiring Manager Screen'), ('technical_screen', 'Technical Screen'), ('final_loop', 'Final Loop')], max_length=50),
        ),
    ]
