# Generated by Django 5.2.7 on 2025-12-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_alter_applicationstatus_state_alter_interview_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['-relevance']},
        ),
    ]
