# Generated by Django 5.2.7 on 2025-12-05 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_alter_requirement_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewProcessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('offer', 'Offer'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('ghosted', 'Ghosted'), ('withdrew', 'Withdrew')], max_length=50)),
                ('outcome_date', models.DateField(help_text='Date when the outcome was determined or notification was received')),
                ('notes', models.TextField(blank=True, help_text='Optional context about the outcome (e.g., feedback received, reason for withdrawal)')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_process_status', to='tracker.application')),
            ],
            options={
                'verbose_name': 'Interview Process Status',
                'verbose_name_plural': 'Interview Process Statuses',
            },
        ),
    ]
