# Generated by Django 5.2.7 on 2025-12-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_interviewprocessstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='focus',
            field=models.CharField(blank=True, choices=[('coding', 'Coding'), ('system_design', 'System Design'), ('behavioral', 'Behavioral'), ('hiring_manager', 'Hiring Manager'), ('refactoring', 'Refactoring / Code Quality')], max_length=50),
        ),
    ]
