# Generated by Django 5.2.7 on 2025-12-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_alter_interview_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='external_job_id',
            field=models.CharField(blank=True, db_index=True, help_text='Company-provided job ID from the job listing.', max_length=64, null=True),
        ),
    ]
