# Generated by Django 5.2.7 on 2025-12-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_job_external_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('associate', 'Associate'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('Senior', 'Senior')], max_length=16),
        ),
    ]
