# Generated by Django 5.2.7 on 2025-12-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_alter_job_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('associate', 'Associate'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('senior', 'Senior')], max_length=16),
        ),
    ]
