# Generated by Django 5.2.7 on 2025-12-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tracker', '0023_job_source'), ('tracker', '0024_alter_job_source')]

    dependencies = [
        ('tracker', '0022_alter_job_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('company_site', 'Company Site'), ('indeed', 'Indeed'), ('internal_recruiter', 'Internal Recruiter'), ('external_recruiter', 'External Recruiter / Headhunter')], default='', max_length=64),
        ),
    ]
