# Generated by Django 5.2.7 on 2025-12-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_job_source_squashed_0024_alter_job_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('company_site', 'Company Site'), ('indeed', 'Indeed'), ('internal_recruiter', 'Internal Recruiter'), ('external_recruiter', 'External Recruiter / Headhunter')], max_length=64),
        ),
    ]
