# Generated by Django 5.2.7 on 2025-12-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_alter_job_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='raw_jd_text',
            field=models.TextField(blank=True, help_text='Original job description text. Used for interview prep generation and enables future re-parsing.'),
        ),
    ]
