# Generated by Django 5.2.7 on 2025-12-23 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_job_raw_jd_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPreparationBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted_jd', models.TextField(help_text='Markdown-formatted job description with bolded callback drivers')),
                ('company_context', models.TextField(help_text='What company does, products, mission, why team exists')),
                ('primary_drivers', models.TextField(help_text='1-3 key reasons resume passed screening, with justifications')),
                ('background_narrative', models.TextField(help_text='Opening line, core narrative, forward hook (markdown formatted)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_prep_base', to='tracker.application')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_questions', models.TextField(help_text='3-5 predicted questions with intent + STAR answers (markdown)')),
                ('interviewer_questions', models.TextField(help_text="5 strategic questions with 'why this works' explanations (markdown)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preparation', to='tracker.interview')),
            ],
            options={
                'unique_together': {('interview',)},
            },
        ),
    ]
