# Generated by Django 5.2.7 on 2025-12-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_alter_llmrequestlog_call_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmrequestlog',
            name='call_type',
            field=models.CharField(choices=[('generate_interview_prep_base', 'Generate Interview Prep Base'), ('generate_interview_prep_specific', 'Generate Interview Prep Specific'), ('parse_jd', 'Parse Job Description'), ('resume_bullets', 'Resume Bullets'), ('resume_skills', 'Resume Skills')], max_length=32),
        ),
    ]
