# Generated by Django 5.2.7 on 2026-01-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_alter_llmrequestlog_call_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewpreparation',
            name='resume_defense_prep',
            field=models.TextField(default='', help_text='Resume bullet defense strategies (markdown)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewpreparation',
            name='technical_deep_dives',
            field=models.TextField(default='todo', help_text='Targeted technical deep dives with prepared explanations (markdown)'),
            preserve_default=False,
        ),
    ]
