# Generated by Django 5.2.7 on 2026-01-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_interviewpreparation_resume_defense_prep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='focus',
            field=models.CharField(blank=True, choices=[('coding', 'Coding'), ('system_design', 'System Design'), ('behavioral', 'Behavioral'), ('hiring_manager', 'Hiring Manager'), ('refactoring', 'Refactoring / Code Quality'), ('case', 'Business Case'), ('data_pipeline_build', 'Data Pipeline Build'), ('data_pipeline_design', 'Data Pipeline Design')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='stage',
            field=models.CharField(choices=[('recruiter_screen', 'Recruiter Screen'), ('hiring_manager_screen', 'Hiring Manager Screen'), ('technical_screen', 'Technical Screen'), ('prep_call', 'Prep/Logistics Call'), ('final_loop', 'Final Loop')], max_length=50),
        ),
    ]
