# Generated by Django 5.2.7 on 2026-01-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_alter_interview_focus_alter_interview_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewpreparation',
            name='prep_plan',
            field=models.TextField(blank=True, help_text='Sequential, prioritized preparation roadmap (markdown)'),
        ),
    ]
