# Generated by Django 5.2.7 on 2026-01-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_interviewpreparation_prep_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewpreparationbase',
            name='resume_defense_prep',
            field=models.TextField(default='todo', help_text='Resume bullet defense strategies (markdown)'),
            preserve_default=False,
        ),
    ]
