# Generated by Django 5.2.7 on 2026-01-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0033_interviewpreparationbase_resume_defense_prep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewpreparation',
            name='resume_defense_prep',
        ),
    ]
