# Generated by Django 5.2.7 on 2026-01-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_remove_interviewpreparation_resume_defense_prep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-scheduled_at']},
        ),
    ]
