# Generated by Django 5.2.7 on 2026-02-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_alter_interview_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='stage',
            field=models.CharField(choices=[('recruiter_screen', 'Recruiter Screen'), ('hiring_manager_screen', 'Hiring Manager Screen'), ('technical_screen', 'Technical Screen'), ('prep_call', 'Prep/Logistics Call'), ('final_loop', 'Final Loop'), ('team_match', 'Team Match')], max_length=50),
        ),
    ]
