# Generated by Django 5.2.7 on 2026-02-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_alter_interview_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='format',
            field=models.CharField(blank=True, choices=[('phone_call', 'Phone Call'), ('virtual_meeting', 'Virtual Meeting'), ('onsite', 'Onsite')], max_length=50),
        ),
    ]
